config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'list', to: 'cash_machines#all'
  # get 'result', to: 'cash_machines#find_nearest'
  # get 'chetotam', to: 'cash_machines#chetotam'

  resources :cash_machines, except: [:update, :edit] do
    post 'find', on: :collection
  end

  root 'cash_machines#index'

  match '/', to: 'cash_machines#index', via: 'get'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cash_machine.rb
class CashMachine < ApplicationRecord
  validates :longitude, numericality: true
  validates :latitude, numericality: true

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cash_machines_controller.rb
# frozen_string_literal: true

class CashMachinesController < ApplicationController
  before_action :set_location, only: [:destroy, :show]

  def index
    @cash_machines = CashMachine.all
  end

  def new
    @cash_machine = CashMachine.new
  end

  def show; end

  def create
    @cash_machine = CashMachine.new(location_params)
    if @cash_machine.save
      flash[:success] = 'ATM added!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def find
    @cash_machines = CashMachine.near([location_params[:latitude], location_params[:longitude]], 50, units: :km)
                                .limit(5)
  end

  def destroy
    @cash_machine.destroy
    redirect_to root_path
  end

  private

  def set_location
    @cash_machine = CashMachine.find(params[:id])
  end

  def location_params
    params.require(:cash_machine).permit(:title, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cash_machines_helper.rb
module CashMachinesHelper
end

app/views/cash_machines/_cash_machine.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tr>
    <td><%= @cash_machine.title %></td>
    <td><%= @cash_machine.latitude %></td>
    <td><%= @cash_machine.longitude %></td>
    <td><%= @cash_machine.address %></td>
    <td><%= link_to 'Destroy', @cash_machine, method: :delete %></td>
  </tr>
</table>
<hr>
<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@cash_machine.latitude},#{@cash_machine.longitude}&markers=#{@cash_machine.latitude},#{@cash_machine.longitude}&zoom=14&size=640x400&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8",
              class: 'img-fluid img-rounded', alt: "#{@cash_machine.title} on the map"%>
<hr>

app/views/cash_machines/_form.html.erb
<%= form_for @cash_machine do |f| %>
  <fieldset class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :latitude %>
    <%= f.text_field :latitude, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :longitude %>
    <%= f.text_field :longitude, class: "form-control" %>
  </fieldset>

  <%= f.submit 'Add!', class: 'btn btn-primary' %>
<% end %>

app/views/cash_machines/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
    </tr>
  </thead>

  <tbody id="CashMachinesTable">
    <% @cash_machines.each do |cash_machine| %>
      <tr>
        <td><%= link_to cash_machine.title, cash_machine_path(cash_machine) %></td>
        <td><%= cash_machine.latitude %></td>
        <td><%= cash_machine.longitude %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cash_machines/_search_form.html.erb
<%= form_for(:cash_machine, url: find_cash_machines_path) do |f| %>

  <fieldset class="form-group">
    <%= f.label :latitude %>
    <%= f.text_field :latitude, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :longitude %>
    <%= f.text_field :longitude, class: "form-control" %>
  </fieldset>

  <%= f.submit 'Find ATM!', class: 'btn btn-primary' %>
<% end %>

app/views/cash_machines/_search_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Distance</th>
    </tr>
  </thead>

  <tbody id="CashMachinesTable">
    <% @cash_machines.each do |cash_machine| %>
      <tr>
        <td><%= link_to cash_machine.title, cash_machine_path(cash_machine) %></td>
        <td><%= cash_machine.latitude %></td>
        <td><%= cash_machine.longitude %></td>
        <td><%= cash_machine.distance_to([params[:cash_machine][:latitude],
                                          params[:cash_machine][:longitude]]).round(2) %>km</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cash_machines/find.html.erb
<header><h1 class="display-4">Search results</h1></header>

<%= render 'search_list' %>

<%= link_to 'Return', root_path, class: 'btn btn-primary btn-lg' %>

app/views/cash_machines/index.html.erb
<header><h1 class="display-4">List of all ATMs</h1></header>

<%= render 'list' %>

<%= link_to 'Add new ATM', new_cash_machine_path, class: 'btn btn-primary btn-lg' %>

<h1 class="display-4">Find 5 nearest ATMs:</h1>

<%= render 'search_form' %>

app/views/cash_machines/new.html.erb
<header><h1 class="display-4">Add Place</h1></header>

<%= render 'form' %>

app/views/cash_machines/show.html.erb
<header><h1 class="display-4">ATM №<%=@cash_machine.id%></h1></header>

<%= render 'cash_machine' %>


<%= link_to 'Return', root_path, class: 'btn btn-primary btn-lg' %>

app/views/layouts/_footer.html.erb
<footer>
<nav id="mainNav" class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <div>
      <ul class="nav navbar-nav">
        <li>
          <a class="navbar-brand page-scroll" href="#page-top">Copyright © Dyachenko Vladislav</a>
        </li>
      </ul>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a class="page-scroll btn-github" href="https://github.com/wowinter13"><span class="fa fa-github"></span>wowinter13</a>
        </li>
        <li>
          <a href="https://vk.com/axscdv">VK</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rocketbankomat</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>

</html>